### ISSUE TITLE
idiot-proof installation instruction please

### ISSUE THREAD

**Issue by horstjens** [salt-die/nurses_2#1]
sadly I can not even get the examples running because i fail already at installation:

I installed the latest version of cython

using popOS linux, installed with "sudo python3.10 setup.py install"

i get this error msg:

> Using /usr/lib/python3.10/dist-packages/opencv_python-4.5.5.62-py3.10-linux-x86_64.egg
> Finished processing dependencies for nurses-2==0.1.2
> Exception ignored in atexit callback: <bound method _Cache.cache_flush of <numpy.distutils.ccompiler_opt.CCompilerOpt object at 0x7f7f5e48af50>>
> Traceback (most recent call last):
>   File "/tmp/easy_install-o3iwbut2/numpy-1.22.0/numpy/distutils/ccompiler_opt.py", line 817, in cache_flush
>   File "/tmp/easy_install-o3iwbut2/numpy-1.22.0/numpy/distutils/ccompiler_opt.py", line 647, in dist_log
>   File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 140, in <module>
>     from . import core
>   File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 48, in <module>
>     raise ImportError(msg)
> ImportError: 
> 
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> 
> Importing the numpy C-extensions failed. This error can happen for
> many reasons, often due to issues with your setup or how NumPy was
> installed.
> 
> We have compiled some common reasons and troubleshooting tips at:
> 
>     https://numpy.org/devdocs/user/troubleshooting-importerror.html
> 
> Please note and check the following:
> 
>   * The Python version is: Python3.10 from "/usr/bin/python3.10"
>   * The NumPy version is: "1.19.5"
> 
> and make sure that they are the versions you expect.
> Please carefully study the documentation linked above for further help.
> 
> Original error was: No module named 'numpy.core._multiarray_umath'
> 
> Exception ignored in atexit callback: <bound method _Cache.cache_flush of <numpy.distutils.ccompiler_opt.CCompilerOpt object at 0x7f7f5e6cd4e0>>
> Traceback (most recent call last):
>   File "/tmp/easy_install-o3iwbut2/numpy-1.22.0/numpy/distutils/ccompiler_opt.py", line 817, in cache_flush
>   File "/tmp/easy_install-o3iwbut2/numpy-1.22.0/numpy/distutils/ccompiler_opt.py", line 647, in dist_log
>   File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 140, in <module>
>     from . import core
>   File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 48, in <module>
>     raise ImportError(msg)
> ImportError: 
> 
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> 
> Importing the numpy C-extensions failed. This error can happen for
> many reasons, often due to issues with your setup or how NumPy was
> installed.
> 
> We have compiled some common reasons and troubleshooting tips at:
> 
>     https://numpy.org/devdocs/user/troubleshooting-importerror.html
> 
> Please note and check the following:
> 
>   * The Python version is: Python3.10 from "/usr/bin/python3.10"
>   * The NumPy version is: "1.19.5"
> 
> and make sure that they are the versions you expect.
> Please carefully study the documentation linked above for further help.
> 
> Original error was: No module named 'numpy.core._multiarray_umath'
> 
> 
> 
>

**Comment by salt-die** [comment]
The numpy version seems incorrect. Numpy below 1.21 won't work with python 3.10. I'm not sure why this happened though. I'll look into it.  Can you try to upgrade numpy separately, `python -m pip install --upgrade numpy`?

**Comment by horstjens** [comment]
thank you for the help @salt-die  !
I was able to made some progress:
I could upgrade numpy  using python3.10 to numpy-1.22.0 and got this message:
```
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nurses-2 0.1.2 requires wcwidth>=0.2.5, but you have wcwidth 0.1.9 which is incompatible.
Successfully installed numpy-1.22.0

```
I could then  install nurses2 using "sudo python3.10 pip install setup.py"

I could run those examples sucessfull from the examples folder:
- brailleimage  ( i see some colorful picture)
- explodinglogo 
- coding_rain
- digital_clock
- explodinglogo_redux
- image
- key_presses
- mouse_events
- navier_stokes
- parallax
- paste
- red_blood_cell_diffusion
- scatter
- scroll_view
- slider
- tile
- stablefluid (after installing scipy using "python3.10 -m pip install scipy")
-cloth
-fluid
-minesweeper
-raycaster
-rubiks
-sandbox
-tetris


but "bouncing_widgets" gives me this error message:
```
Traceback (most recent call last):
  File "/home/horst/code/nurses_2-main/examples/bouncing_widgets.py", line 121, in <module>
    MyApp().run()
  File "/usr/lib/python3.10/dist-packages/nurses_2-0.1.2-py3.10.egg/nurses_2/app.py", line 51, in run
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/dist-packages/nurses_2-0.1.2-py3.10.egg/nurses_2/app.py", line 119, in _run_async
  File "/home/horst/code/nurses_2-main/examples/bouncing_widgets.py", line 117, in on_start
    widget_overlap.add_text("True " if widget_1.collides_widget(widget_2) else "False")
  File "/usr/lib/python3.10/dist-packages/nurses_2-0.1.2-py3.10.egg/nurses_2/widgets/_widget_base.py", line 234, in collides_widget
NameError: name 'other' is not defined. Did you mean: 'iter'?

```




I could run those examples using

**Comment by salt-die** [comment]
I fixed the error for the `collides_widget` method that the `bouncing_widgets` example used in the last release! It was just a simple name error! Try nurses v0.1.3.  I'll probably have new releases every few days as I continue to fix bugs and add features.

**Comment by horstjens** [comment]
bouncing widgets works now!
