### ISSUE TITLE
Object has no attribute `asciicast_path`

### ISSUE THREAD

**Issue by Froloket64** [salt-die/nurses_2#5]
I was writing a simple launcher for a game (Devil Daggers) with mods and maps support and I found a strange behavior. The app worked fine, but when I introduced args to the app class instance (`Launcher(custom_path, dd_path).run()`) it started throwing the following exception:
```
Traceback (most recent call last):
  File "/home/froloket/Code/Python/DD Launcher/main.py", line 94, in <module>
    Launcher(custom_path, dd_path).run()
  File "/home/froloket/.local/lib/python3.10/site-packages/nurses_2/app.py", line 135, in run
    asyncio.run(self._run_async())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/froloket/.local/lib/python3.10/site-packages/nurses_2/app.py", line 153, in _run_async
    with io(self.asciicast_path) as (env_in, env_out):
AttributeError: 'Launcher' object has no attribute 'asciicast_path'
```
I'll repeat, the problem arises once the args are added, just `Launcher().run()` works (with the `__init__()` changed respectively)
I took a glance at the src, but haven't noticed anything weird so far.

Paste: https://pastebin.com/9UB0Ybp1 _(don't worry about the logic, it's vastly incomplete)_

Thanks in advance

**Comment by Froloket64** [comment]
Welp, I think I got it.
The `App` base class has an `__init__ method that initializes the `self.ascii_path` ([src](https://github.com/salt-die/nurses_2/blob/1ffaf38af706e4961db30b5f01784e3f42e15611/nurses_2/app.py#L108)). So, when I overwrite the `__init__` method in my class instance that inherits `App` the `App.__init__` never gets executed. The solution is simple (but maybe not too elegant):
``` py
class Launcher(App):
    def __init__(self, custom_path, dd_path):
        super().__init__()

        ... # Actual __init__ code
```

**Comment by salt-die** [comment]
> ```python
> class Launcher(App):
>     def __init__(self, custom_path, dd_path):
>         super().__init__()
> 
>         ... # Actual __init__ code
> ```

This is the correct way to make sure the base gets initialized correctly. If you want to also pass arguments and keyword arguments to the base class, you would make a slight change:
```py
class Launcher(App):
    def __init__(self, custom_path, dd_path, *args, **kwargs):
        super().__init__(*args, **kwargs)
        ...
```
Alternatively, you can pass your own arguments to the base:
```py
class Launcher(App):
    def __init__(self, custom_path, dd_path):
        super().__init__(title="My Game!")
        ...
```
