### ISSUE TITLE
[Question] Updating `FileChooser`'s root

### ISSUE THREAD

**Issue by Froloket64** [salt-die/nurses_2#6]
Is there a way to update the `FileChooser`'s root directory/node?

I've tried setting the `root_node`  
``` py
chooser.view.root_node = Path("other/path")
```
and calling
``` py
chooser.view.update_tree_layout()
```
But nothing seemed to do the trick

Also, Happy New Year)

**Comment by salt-die** [comment]
try:
```py
chooser.view.root_node = FileViewNode(Path("other/path"))
```
and then updating.

**Comment by salt-die** [comment]
I tested this by modify `examples/basic/filechooser.py` to the following:
```py
import asyncio

from pathlib import Path

from nurses_2.app import App
from nurses_2.widgets.file_chooser import FileChooser, FileViewNode
from nurses_2.widgets.text_widget import TextWidget

ASSETS = Path(__file__).parent.parent / "assets"

class FileApp(App):
    async def on_start(self):
        label = TextWidget(size=(1, 50), pos=(0, 26))
        select_callback = lambda path: label.add_text(f"{f'{path.name} selected!':<50}"[:50])
        fc = FileChooser(
            root_dir=ASSETS,
            size=(20, 25),
            size_hint=(1.0, None),
            select_callback=select_callback,
        )
        self.add_widgets(label, fc)

        await asyncio.sleep(5)

        fc.view.root_node = FileViewNode(Path(__file__).parent.parent.parent)
        fc.view.root_node.tree_view = fc.view
        fc.view.root_node.toggle()
        fc.view.update_tree_layout()


FileApp(title="File Chooser Example").run()
```
I may add a more convenient method of changing the root soon.

**Comment by Froloket64** [comment]
> ``` py
> chooser.view.root_node = FileViewNode(Path("other/path"))
> chooser.view.root_node.tree_view = chooser.view
> chooser.view.root_node.toggle()
> chooser.view.update_tree_layout()
> ```


Oh. I honestly have no idea how I started assigning a `Path` to `root_node`, but yeah...
But I wouldn't have come up with the rest, so thanks a lot.

**Comment by salt-die** [comment]
`FileChooser` now has a `root_dir` property that can be set with any `Path`.  `examples/basic/file_chooser.py` updated to give an example.
