### ISSUE TITLE
Just a static, replaceable text widget

### ISSUE THREAD

**Issue by Froloket64** [salt-die/nurses_2#8]
Hey, for the last couple of days I've been struggling to use any of the widgets You present in the library (`text_widget`, `text_pad`, `textbox`) to **just place some text**. Of course, I can just use a `textbox`, fill it using its `textbox.text` and block its user input capabilities, but that last part concerns me the most, it makes the code kind of uglier.

Would be great if you could implement such a widget (has `self.text`, but no user input), or hint me at what I'm doing wrong here...

**Comment by salt-die** [comment]
The normal way to do this is to use a TextWidget and fill its canvas with `add_text` which now works with multiline text.  It doesn't resize the widget to fit the text though. I could maybe be convinced to add a `text` property to TextWidget that will grow or shrink the Widget to fit the text.

Currently working on a breaking change to `TextWidget` canvas. They'll soon be structured np arrays instead of dtype object. This breaks everything, so gimme a few days to revisit the issue.

**Comment by Froloket64** [comment]
> The normal way to do this is to use a TextWidget and fill its canvas with `add_text` which now works with multiline text

Could you expand a bit on the `add_text` part. It seems like every time I'm trying to pass any string to it, it only assigns the last char of the string.

Also, I'm using `TextWidget.add_text` here, but I noticed that there's a note about `widgets.text_widget_data_structures.add_text` in the docs, however I'm not able to import it. Moreover, on the `widgets.text_widget` page there doesn't seem to show a `add_text` method of the class, only `add_str`, which again doesn't in fact seem to exist. But that's just (?) docs-related issues.

**Comment by salt-die** [comment]
You're right, I haven't made a release with the latest changes.  `add_text` was made a separate function recently (to sort of mirror `composite` for GraphicWidgets) and the `add_text` method was changed to `add_str`.   A new release will come in a day or two... I have some more breaking changes and I figured I should just release it all at once.  Once released it will work something like:
```py
add_text(my_widget.canvas, "Mary had a little lamb, /n Her fleece was white as snow...")
```
This will allow one to pass views of the canvas as well, so for, say, vertical text you could do:
```py
add_text(my_widget.canvas.T, ...)
```

**Comment by Froloket64** [comment]
I see. Waiting for the release then!

Thanks for maintaining the project btw, it's really a pleasure to work with.
